In [3]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [8]:
# lets check date functions here
%%sql

SELECT
  orderdate,
  DATE_TRUNC('month', orderdate) AS order_month
FROM sales
  limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate               order_month
0  2015-01-01 2015-01-01 00:00:00+00:00
1  2015-01-01 2015-01-01 00:00:00+00:00
2  2015-01-01 2015-01-01 00:00:00+00:00
3  2015-01-01 2015-01-01 00:00:00+00:00
4  2015-01-01 2015-01-01 00:00:00+00:00
5  2015-01-01 2015-01-01 00:00:00+00:00
6  2015-01-01 2015-01-01 00:00:00+00:00
7  2015-01-01 2015-01-01 00:00:00+00:00
8  2015-01-01 2015-01-01 00:00:00+00:00
9  2015-01-01 2015-01-01 00:00:00+00:00

In [9]:
%%sql

SELECT
  orderdate,
  DATE_TRUNC('month', orderdate)::date AS order_month
FROM sales
  limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate order_month
0  2015-01-01  2015-01-01
1  2015-01-01  2015-01-01
2  2015-01-01  2015-01-01
3  2015-01-01  2015-01-01
4  2015-01-01  2015-01-01
5  2015-01-01  2015-01-01
6  2015-01-01  2015-01-01
7  2015-01-01  2015-01-01
8  2015-01-01  2015-01-01
9  2015-01-01  2015-01-01

In [12]:
# calculating net revenue by order month

%%sql

SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(exchangerate*quantity*netprice) AS net_revenue
FROM sales
  GROUP BY
    order_month
  ORDER BY
    order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue
0    2015-01-01    384092.66
1    2015-02-01    706374.12
2    2015-03-01    332961.59
3    2015-04-01    160767.00
4    2015-05-01    548632.63
..          ...          ...
107  2023-12-01   2928550.93
108  2024-01-01   2677498.55
109  2024-02-01   3542322.55
110  2024-03-01   1692854.89
111  2024-04-01    483851.39

[112 rows x 2 columns]

In [14]:
# counting distinct unique customers using customer key

%%sql

SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(exchangerate*quantity*netprice) AS net_revenue,
  COUNT(DISTINCT customerkey) AS unique_customers
FROM sales
  GROUP BY
    order_month
  ORDER BY
    order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  unique_customers
0    2015-01-01    384092.66               200
1    2015-02-01    706374.12               291
2    2015-03-01    332961.59               139
3    2015-04-01    160767.00                78
4    2015-05-01    548632.63               236
..          ...          ...               ...
107  2023-12-01   2928550.93              1484
108  2024-01-01   2677498.55              1340
109  2024-02-01   3542322.55              1718
110  2024-03-01   1692854.89               877
111  2024-04-01    483851.39               246

[112 rows x 3 columns]

In [19]:
# using the TO_CHAR function


%%sql

SELECT
  TO_CHAR(orderdate, 'MM-YY') AS month_year,
  SUM(exchangerate*quantity*netprice) AS net_revenue
FROM sales

GROUP BY month_year
ORDER BY month_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    month_year  net_revenue
0        01-15    384092.66
1        01-16    835484.26
2        01-17    996797.10
3        01-18   1675202.32
4        01-19   3082448.20
..         ...          ...
107      12-19   2696740.22
108      12-20    524808.49
109      12-21   3643597.36
110      12-22   4238010.83
111      12-23   2928550.93

[112 rows x 2 columns]

In [22]:
# using the TO_CHAR function, unique customers by month


%%sql

SELECT
  TO_CHAR(orderdate, 'MM-YY') AS month_year,
  COUNT(DISTINCT customerkey) AS unique_customer_count
FROM sales

GROUP BY month_year
ORDER BY month_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    month_year  unique_customer_count
0        01-15                    200
1        01-16                    323
2        01-17                    332
3        01-18                    586
4        01-19                   1093
..         ...                    ...
107      12-19                   1003
108      12-20                    241
109      12-21                   1435
110      12-22                   1960
111      12-23                   1484

[112 rows x 2 columns]