In [11]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [24]:
# now we will try to extract day, month and year from the orderdate using DAT_PART function

%%sql

SELECT
  DATE_PART('year', orderdate) AS order_YEAR,
  DATE_PART('month', orderdate) AS order_MONTH,
  DATE_PART('day', orderdate) AS order_DAY
FROM sales
limit 10
-- we got a problem of decimal places, BTW we can solve that too

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   order_year  order_month  order_day
0     2015.00         1.00       1.00
1     2015.00         1.00       1.00
2     2015.00         1.00       1.00
3     2015.00         1.00       1.00
4     2015.00         1.00       1.00
5     2015.00         1.00       1.00
6     2015.00         1.00       1.00
7     2015.00         1.00       1.00
8     2015.00         1.00       1.00
9     2015.00         1.00       1.00

In [25]:
# by using EXTRACT function we can get desired result

%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS year,
  EXTRACT(MONTH FROM orderdate) AS month,
  EXTRACT(DAY FROM orderdate) AS day
FROM sales

LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   year month day
0  2015     1   1
1  2015     1   1
2  2015     1   1
3  2015     1   1
4  2015     1   1
5  2015     1   1
6  2015     1   1
7  2015     1   1
8  2015     1   1
9  2015     1   1

In [26]:
# we can use EXTRACT function to group them according to net revenue

%%sql

SELECT
  EXTRACT(YEAR FROM s.orderdate) AS order_YEAR,
  EXTRACT(MONTH FROM s.orderdate) AS order_MONTH,
  SUM(s.netprice*s.exchangerate*s.quantity) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  order_YEAR,
  order_MONTH
ORDER BY
  order_YEAR,
  order_MONTH

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [27]:
# now we will try to include category for more detail
%%sql

SELECT
  EXTRACT(YEAR FROM s.orderdate) AS order_YEAR,
  p.categoryname,
  SUM(s.netprice*s.exchangerate*s.quantity) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  order_YEAR,
  p.categoryname
ORDER BY
  order_YEAR,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

80 rows affected.

   order_year                   categoryname  net_revenue
0        2015                          Audio    170872.15
1        2015        Cameras and camcorders    1828111.71
2        2015                    Cell phones    591513.47
3        2015                      Computers   2139915.71
4        2015                 Games and Toys     45404.59
..        ...                            ...          ...
75       2024                      Computers   2957039.62
76       2024                 Games and Toys     85867.75
77       2024                Home Appliances   1320161.48
78       2024  Music, Movies and Audio Books    592662.15
79       2024                   TV and Video    910738.50

[80 rows x 3 columns]

In [29]:
# using now function

%%sql
  SELECT NOW()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2026-03-22 09:30:06.018184+00:00

In [30]:
%%sql
  SELECT CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-03-22

In [36]:
%%sql

SELECT
  CURRENT_DATE,
  s.orderdate,
  p.categoryname,
  SUM(s.netprice*s.exchangerate*s.quantity) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

23496 rows affected.

      current_date   orderdate                   categoryname  net_revenue
0       2026-03-22  2015-01-01                          Audio      1555.67
1       2026-03-22  2015-01-01        Cameras and camcorders       4977.13
2       2026-03-22  2015-01-01                      Computers      3066.35
3       2026-03-22  2015-01-01                 Games and Toys       163.87
4       2026-03-22  2015-01-01                Home Appliances      1152.57
...            ...         ...                            ...          ...
23491   2026-03-22  2024-04-20                      Computers     58353.68
23492   2026-03-22  2024-04-20                 Games and Toys      1744.30
23493   2026-03-22  2024-04-20                Home Appliances      1562.04
23494   2026-03-22  2024-04-20  Music, Movies and Audio Books      4949.43
23495   2026-03-22  2024-04-20                   TV and Video      9841.91

[23496 rows x 4 columns]

In [38]:
# now selecting only for last 5 years of records

%%sql

SELECT
  CURRENT_DATE,
  s.orderdate,
  p.categoryname,
  SUM(s.netprice*s.exchangerate*s.quantity) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE EXTRACT(YEAR FROM s.orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) -5
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

     current_date   orderdate                   categoryname  net_revenue
0      2026-03-22  2021-01-01                          Audio      1206.67
1      2026-03-22  2021-01-01        Cameras and camcorders       2228.75
2      2026-03-22  2021-01-01                    Cell phones     10582.00
3      2026-03-22  2021-01-01                      Computers     12718.95
4      2026-03-22  2021-01-01                 Games and Toys       235.53
...           ...         ...                            ...          ...
8952   2026-03-22  2024-04-20                      Computers     58353.68
8953   2026-03-22  2024-04-20                 Games and Toys      1744.30
8954   2026-03-22  2024-04-20                Home Appliances      1562.04
8955   2026-03-22  2024-04-20  Music, Movies and Audio Books      4949.43
8956   2026-03-22  2024-04-20                   TV and Video      9841.91

[8957 rows x 4 columns]