In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [4]:
# assigning cohort year with their customer key

%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey cohort_year
0           15        2021
1          180        2018
2          180        2018
3          180        2018
4          185        2019
5          243        2016
6          387        2018
7          387        2018
8          387        2018
9          387        2018

In [6]:
# adding purchasing year by their customerkey

%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey cohort_year purchase_year
0           15        2021          2021
1          180        2018          2018
2          180        2018          2023
3          180        2018          2023
4          185        2019          2019
5          243        2016          2016
6          387        2018          2018
7          387        2018          2018
8          387        2018          2021
9          387        2018          2018

In [15]:
# now we want to find no. of customers with respective years (we will use CTE here)

%%sql

WITH year_data AS(
  SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
  sales
)

SELECT DISTINCT
  cohort_year,
  purchase_year,
  -- now will apply window function
  COUNT(customerkey) OVER (PARTITION BY cohort_year, purchase_year) AS num_customers
FROM year_data
ORDER BY
  cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

In [19]:
# now we will move forward to get customer's lifetime value
%%sql

 SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(netprice*exchangerate*quantity) AS customer_LTV
FROM
  sales
GROUP BY
  customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv
0          1603477        2021        136.62
1          2089398        2018         98.39
2           300840        2019       1221.78
3           418360        2018       2602.96
4          1217159        2022       1420.44
...            ...         ...           ...
49482        53347        2019       4924.74
49483       929360        2016        106.60
49484       560047        2020       1569.99
49485      1110282        2023       2384.39
49486      1573639        2016       6973.42

[49487 rows x 3 columns]

In [20]:
# using CTE

%%sql

WITH cohort AS(
  SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(netprice*exchangerate*quantity) AS customer_LTV
FROM
  sales
GROUP BY
  customerkey
)

SELECT
  *
FROM cohort
LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   customerkey cohort_year  customer_ltv
0           15        2021       2217.41
1          180        2018       2510.22
2          185        2019       1395.52
3          243        2016        287.67
4          387        2018       4655.84

In [23]:
# adding average cohort life time value

%%sql

WITH cohort AS(
  SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(netprice*exchangerate*quantity) AS customer_LTV
FROM
  sales
GROUP BY
  customerkey
)

SELECT
  customerkey,
  cohort_year,
  customer_LTV,
  AVG(customer_LTV) OVER (PARTITION BY cohort_year) avg_cohort_LTV
FROM cohort
ORDER BY
  cohort_year,
  customerkey

LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   customerkey cohort_year  customer_ltv  avg_cohort_ltv
0         4376        2015        182.00         5271.59
1         4403        2015       9530.35         5271.59
2         4925        2015       6078.08         5271.59
3         5729        2015        192.16         5271.59
4         6048        2015       1903.89         5271.59

In [28]:
# calculating average LTV For individual years
%%sql

WITH cohort AS(
  SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(netprice*exchangerate*quantity) AS customer_LTV
FROM
  sales
GROUP BY
  customerkey),
  cohort_summary AS (
    SELECT
  customerkey,
  cohort_year,
  customer_LTV,
  AVG(customer_LTV) OVER (PARTITION BY cohort_year) avg_cohort_LTV
FROM cohort
ORDER BY
  cohort_year,
  customerkey
  )

SELECT DISTINCT
  cohort_year,
  avg_cohort_LTV
FROM
  cohort_summary
ORDER BY
  cohort_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_cohort_ltv
0        2015         5271.59
1        2016         5404.92
2        2017         5403.08
3        2018         4896.64
4        2019         4731.95
5        2020         3933.32
6        2021         3943.33
7        2022         3315.52
8        2023         2543.18
9        2024         2037.55