In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

SELECT
  customerkey,
  orderdate,
  (quantity*netprice*exchangerate) AS net_revenue,
  COUNT(*) OVER (PARTITION BY customerkey ORDER BY orderdate) AS running_order_count
FROM sales
LIMIT 15

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

15 rows affected.

    customerkey   orderdate  net_revenue  running_order_count
0            15  2021-03-08      2217.41                    1
1           180  2018-07-28       525.31                    1
2           180  2023-08-28        71.36                    3
3           180  2023-08-28      1913.55                    3
4           185  2019-06-01      1395.52                    1
5           243  2016-05-19       287.67                    1
6           387  2018-12-21        45.62                    4
7           387  2018-12-21      1608.10                    4
8           387  2018-12-21       619.77                    4
9           387  2018-12-21        97.05                    4
10          387  2021-10-30      1265.56                    5
11          387  2023-11-16       362.44                    9
12          387  2023-11-16       446.44                    9
13          387  2023-11-16       180.35                    9
14          387  2023-11-16        30.51                    9

In [8]:
# similarily getting the running average revenue for each customer

%%sql

SELECT
  customerkey,
  orderdate,
  (quantity*netprice*exchangerate) AS net_revenue,
  AVG(quantity*netprice*exchangerate) OVER (PARTITION BY customerkey ORDER BY orderdate) AS running_avg_revenue
FROM sales
LIMIT 15

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

15 rows affected.

    customerkey   orderdate  net_revenue  running_avg_revenue
0            15  2021-03-08      2217.41              2217.41
1           180  2018-07-28       525.31               525.31
2           180  2023-08-28      1913.55               836.74
3           180  2023-08-28        71.36               836.74
4           185  2019-06-01      1395.52              1395.52
5           243  2016-05-19       287.67               287.67
6           387  2018-12-21       619.77               592.64
7           387  2018-12-21        45.62               592.64
8           387  2018-12-21      1608.10               592.64
9           387  2018-12-21        97.05               592.64
10          387  2021-10-30      1265.56               727.22
11          387  2023-11-16       180.35               517.32
12          387  2023-11-16        30.51               517.32
13          387  2023-11-16       362.44               517.32
14          387  2023-11-16       446.44               517.32

In [12]:
# using row number function

%%sql

SELECT
  ROW_NUMBER() OVER() AS row_num,
  *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,7,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,8,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,9,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,10,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [13]:
# to be more specific we can use more criterias for accuracy

%%sql

SELECT
  ROW_NUMBER() OVER(
    ORDER BY orderdate, orderkey, linenumber
  ) AS row_num,
  *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,7,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,8,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,9,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,10,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [17]:
# we cab also use DESC in order by
%%sql

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
    orderdate DESC,
    orderkey DESC,
    linenumber DESC
  ) AS daily_order_num,
  *
FROM sales
# WHERE orderdate > '2015-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,daily_order_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38
1,2,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
2,3,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
3,4,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
4,5,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
5,6,3398034,0,2024-04-20,2024-04-21,664396,999999,1511,1,229.00,199.23,105.31,EUR,0.94
6,7,3398033,2,2024-04-20,2024-04-20,635184,160,1206,3,1560.00,1388.40,516.86,EUR,0.94
7,8,3398033,1,2024-04-20,2024-04-20,635184,160,991,3,268.00,235.84,88.79,EUR,0.94
8,9,3398033,0,2024-04-20,2024-04-20,635184,160,1681,7,6.89,5.93,3.17,EUR,0.94
9,10,3398032,1,2024-04-20,2024-04-25,852158,999999,1651,2,159.99,139.19,73.57,EUR,0.94

In [22]:
# getting order count for specific customers
%%sql

SELECT
  customerkey,
  COUNT(orderkey) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY COUNT(orderkey) DESC) AS total_orders_row_num
FROM sales
GROUP BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  total_orders  total_orders_row_num
0      1834524            31                     1
1      1375597            30                     2
2       249557            27                     3
3       459519            26                     4
4      1495941            26                     5
5      1801215            26                     6
6      1219056            25                     7
7       759419            24                     8
8      1427444            24                     9
9      1876222            24                    10

In [36]:
# getting the rank
%%sql

SELECT
  customerkey,
  DENSE_RANK() OVER(ORDER BY COUNT(orderkey) DESC) AS total_orders_dense_rank, -- included DENSE_RANK() function
  COUNT(orderkey) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY COUNT(orderkey) DESC) AS total_orders_row_num,
  RANK() OVER(ORDER BY COUNT(orderkey) DESC) AS total_orders_rank -- included RANK() function
FROM sales
GROUP BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders_dense_rank,total_orders,total_orders_row_num,total_orders_rank
0,1834524,1,31,1,1
1,1375597,2,30,2,2
2,249557,3,27,3,3
3,459519,4,26,4,4
4,1495941,4,26,5,4
5,1801215,4,26,6,4
6,1219056,5,25,7,7
7,759419,6,24,8,8
8,1427444,6,24,9,8
9,1876222,6,24,10,8