In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue
0   2022-01   3647525.92
1   2022-02   4840124.87
2   2022-03   2801554.72
3   2022-04   1746624.57
4   2022-05   4430652.19
5   2022-06   4777313.11
6   2022-07   3395262.66
7   2022-08   3698942.66
8   2022-09   3854509.88
9   2022-10   3913434.52
10  2022-11   3520601.27
11  2022-12   4238010.83

In [15]:
# applying CTE getting month datas for comparisons

%%sql
with monthly_sales AS (
  SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)

SELECT
  month,
  net_revenue,
  FIRST_VALUE(net_revenue) OVER (ORDER BY month) AS first_month_revenue,

  LAST_VALUE(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_month_revenue,
  NTH_VALUE(net_revenue, 4) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fourth_month_revenue,
  LAG(net_revenue) OVER (ORDER BY month) AS previous_month_revenue,
  LEAD(net_revenue) OVER (ORDER BY month) AS next_month_revenue

FROM monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,last_month_revenue,fourth_month_revenue,previous_month_revenue,next_month_revenue
0,2022-01,3647525.92,3647525.92,4238010.83,1746624.57,NaN,4840124.87
1,2022-02,4840124.87,3647525.92,4238010.83,1746624.57,3647525.92,2801554.72
2,2022-03,2801554.72,3647525.92,4238010.83,1746624.57,4840124.87,1746624.57
3,2022-04,1746624.57,3647525.92,4238010.83,1746624.57,2801554.72,4430652.19
4,2022-05,4430652.19,3647525.92,4238010.83,1746624.57,1746624.57,4777313.11
5,2022-06,4777313.11,3647525.92,4238010.83,1746624.57,4430652.19,3395262.66
6,2022-07,3395262.66,3647525.92,4238010.83,1746624.57,4777313.11,3698942.66
7,2022-08,3698942.66,3647525.92,4238010.83,1746624.57,3395262.66,3854509.88
8,2022-09,3854509.88,3647525.92,4238010.83,1746624.57,3698942.66,3913434.52
9,2022-10,3913434.52,3647525.92,4238010.83,1746624.57,3854509.88,3520601.27
10,2022-11,3520601.27,3647525.92,4238010.83,1746624.57,3913434.52,4238010.83
11,2022-12,4238010.83,3647525.92,4238010.83,1746624.57,3520601.27,NaN

In [20]:
# getting essensials

%%sql
with monthly_sales AS (
  SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)

SELECT
  month,
  net_revenue,
  LAG(net_revenue) OVER (ORDER BY month) AS previous_month_revenue,
  100*(net_revenue - LAG(net_revenue) OVER (ORDER BY month))/ LAG(net_revenue) OVER (ORDER BY month) AS month_over_revenue_growth
FROM monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue  month_over_revenue_growth
0   2022-01   3647525.92                     NaN                        NaN
1   2022-02   4840124.87              3647525.92                      32.70
2   2022-03   2801554.72              4840124.87                     -42.12
3   2022-04   1746624.57              2801554.72                     -37.66
4   2022-05   4430652.19              1746624.57                     153.67
5   2022-06   4777313.11              4430652.19                       7.82
6   2022-07   3395262.66              4777313.11                     -28.93
7   2022-08   3698942.66              3395262.66                       8.94
8   2022-09   3854509.88              3698942.66                       4.21
9   2022-10   3913434.52              3854509.88                       1.53
10  2022-11   3520601.27              3913434.52                     -10.04
11  2022-12   4238010.83              3520601.27                      20.38