In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [10]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue
0   2022-01   3647525.92
1   2022-02   4840124.87
2   2022-03   2801554.72
3   2022-04   1746624.57
4   2022-05   4430652.19
5   2022-06   4777313.11
6   2022-07   3395262.66
7   2022-08   3698942.66
8   2022-09   3854509.88
9   2022-10   3913434.52
10  2022-11   3520601.27
11  2022-12   4238010.83

In [17]:
# applying CTE and using ROW function

%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,

  AVG(net_revenue) OVER (ORDER BY month ROWS CURRENT ROW) AS net_revenue_current, -- applying CURRENT ROW function
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS net_revenue_preceding  -- applying PRECEDING ROW function
FROM
  monthly_sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

     month  net_revenue  net_revenue_current  net_revenue_preceding
0  2022-01   3647525.92           3647525.92             3647525.92
1  2022-02   4840124.87           4840124.87             4243825.40
2  2022-03   2801554.72           2801554.72             3820839.80
3  2022-04   1746624.57           1746624.57             2274089.64
4  2022-05   4430652.19           4430652.19             3088638.38
5  2022-06   4777313.11           4777313.11             4603982.65
6  2022-07   3395262.66           3395262.66             4086287.89
7  2022-08   3698942.66           3698942.66             3547102.66
8  2022-09   3854509.88           3854509.88             3776726.27
9  2022-10   3913434.52           3913434.52             3883972.20

In [30]:
# applying CTE and using multitude of preceding funcitions

%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,

  # AVG(net_revenue) OVER (ORDER BY month ROWS CURRENT ROW) AS net_revenue_current, -- applying CURRENT ROW function
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS net_revenue_preceding_1,  -- getting average of current and previous 1 row
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS net_revenue_preceding_2,  -- getting average of current and previous 2 rows
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS net_revenue_preceding_3   -- getting average of current and previous 3 rows
FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,net_revenue_preceding_1,net_revenue_preceding_2,net_revenue_preceding_3
0,2022-01,3647525.92,3647525.92,3647525.92,3647525.92
1,2022-02,4840124.87,4243825.40,4243825.40,4243825.40
2,2022-03,2801554.72,3820839.80,3763068.51,3763068.51
3,2022-04,1746624.57,2274089.64,3129434.72,3258957.52
4,2022-05,4430652.19,3088638.38,2992943.83,3454739.09
5,2022-06,4777313.11,4603982.65,3651529.95,3439036.15
6,2022-07,3395262.66,4086287.89,4201075.99,3587463.13
7,2022-08,3698942.66,3547102.66,3957172.81,4075542.66
8,2022-09,3854509.88,3776726.27,3649571.74,3931507.08
9,2022-10,3913434.52,3883972.20,3822295.69,3715537.43
10,2022-11,3520601.27,3717017.89,3762848.55,3746872.08
11,2022-12,4238010.83,3879306.05,3890682.21,3881639.12

In [29]:
# conversely FOLLOWING ROW function takes all following rows instead of preceding ones

# applying CTE and using multitude of Following funcitions

%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,

  # AVG(net_revenue) OVER (ORDER BY month ROWS CURRENT ROW) AS net_revenue_current, -- applying CURRENT ROW function
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) AS net_revenue_following_1,  -- getting average of current and next 1 row
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) AS net_revenue_following_2,  -- getting average of current and next 2 rows
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING) AS net_revenue_following_3   -- getting average of current and next 3 rows
FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,net_revenue_following_1,net_revenue_following_2,net_revenue_following_3
0,2022-01,3647525.92,4243825.40,3763068.51,3258957.52
1,2022-02,4840124.87,3820839.80,3129434.72,3454739.09
2,2022-03,2801554.72,2274089.64,2992943.83,3439036.15
3,2022-04,1746624.57,3088638.38,3651529.95,3587463.13
4,2022-05,4430652.19,4603982.65,4201075.99,4075542.66
5,2022-06,4777313.11,4086287.89,3957172.81,3931507.08
6,2022-07,3395262.66,3547102.66,3649571.74,3715537.43
7,2022-08,3698942.66,3776726.27,3822295.69,3746872.08
8,2022-09,3854509.88,3883972.20,3762848.55,3881639.12
9,2022-10,3913434.52,3717017.89,3890682.21,3890682.21
10,2022-11,3520601.27,3879306.05,3879306.05,3879306.05
11,2022-12,4238010.83,4238010.83,4238010.83,4238010.83

In [37]:
# finally comparing both ROW functions


%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,


  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS net_revenue_preceding,  -- getting average of current and previous 1 row
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) AS net_revenue_following   -- getting average of current and next 1 row
FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_preceding  net_revenue_following
0   2022-01   3647525.92             3647525.92             4243825.40
1   2022-02   4840124.87             4243825.40             3820839.80
2   2022-03   2801554.72             3820839.80             2274089.64
3   2022-04   1746624.57             2274089.64             3088638.38
4   2022-05   4430652.19             3088638.38             4603982.65
5   2022-06   4777313.11             4603982.65             4086287.89
6   2022-07   3395262.66             4086287.89             3547102.66
7   2022-08   3698942.66             3547102.66             3776726.27
8   2022-09   3854509.88             3776726.27             3883972.20
9   2022-10   3913434.52             3883972.20             3717017.89
10  2022-11   3520601.27             3717017.89             3879306.05
11  2022-12   4238010.83             3879306.05             4238010.83

In [40]:
# for best practice we take into account last month and next month to calculate rolling
# finally comparing both ROW functions


%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,

  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS net_revenue_rolling  -- getting average of previous 1 row, current and next 1 row
FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_rolling
0   2022-01   3647525.92           4243825.40
1   2022-02   4840124.87           3763068.51
2   2022-03   2801554.72           3129434.72
3   2022-04   1746624.57           2992943.83
4   2022-05   4430652.19           3651529.95
5   2022-06   4777313.11           4201075.99
6   2022-07   3395262.66           3957172.81
7   2022-08   3698942.66           3649571.74
8   2022-09   3854509.88           3822295.69
9   2022-10   3913434.52           3762848.55
10  2022-11   3520601.27           3890682.21
11  2022-12   4238010.83           3879306.05

# UNBOUNDED

In [46]:
# using UNBOUND function

%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,

  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS net_revenue_rolling,  -- taking average of current and all rows
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS net_revenue_current_above,    -- taking average of current and all rows ABOVE
  AVG(net_revenue) OVER (ORDER BY month ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS net_revenue_current_below     -- taking average of current and all rows BELOW

FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,net_revenue_rolling,net_revenue_current_above,net_revenue_current_below
0,2022-01,3647525.92,3738713.10,3647525.92,3738713.10
1,2022-02,4840124.87,3738713.10,4243825.40,3747002.84
2,2022-03,2801554.72,3738713.10,3763068.51,3637690.64
3,2022-04,1746624.57,3738713.10,3258957.52,3730594.63
4,2022-05,4430652.19,3738713.10,3493296.45,3978590.89
5,2022-06,4777313.11,3738713.10,3707299.23,3914010.70
6,2022-07,3395262.66,3738713.10,3662722.58,3770126.97
7,2022-08,3698942.66,3738713.10,3667250.09,3845099.83
8,2022-09,3854509.88,3738713.10,3688056.73,3881639.12
9,2022-10,3913434.52,3738713.10,3710594.51,3890682.21
10,2022-11,3520601.27,3738713.10,3693322.40,3879306.05
11,2022-12,4238010.83,3738713.10,3738713.10,4238010.83

In [53]:
# using UNBOUNDED and LAST VALUE

%%sql

WITH monthly_sales AS (

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity*netprice*exchangerate) AS net_revenue
FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  month
ORDER BY
  month
)


SELECT
  month,
  net_revenue,
  LAST_VALUE(net_revenue) OVER (ORDER BY month) AS last_month_revenue,
  LAST_VALUE(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_month_revenue, -- we got the value (display in all)
  NTH_VALUE(net_revenue, 3) OVER (ORDER BY month) AS third_month_revenue,
  NTH_VALUE(net_revenue, 3) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS third_month_revenue_unbound  -- we got the value (display in all)

FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,last_month_revenue,last_month_revenue,third_month_revenue,third_month_revenue_unbound
0,2022-01,3647525.92,3647525.92,4238010.83,NaN,2801554.72
1,2022-02,4840124.87,4840124.87,4238010.83,NaN,2801554.72
2,2022-03,2801554.72,2801554.72,4238010.83,2801554.72,2801554.72
3,2022-04,1746624.57,1746624.57,4238010.83,2801554.72,2801554.72
4,2022-05,4430652.19,4430652.19,4238010.83,2801554.72,2801554.72
5,2022-06,4777313.11,4777313.11,4238010.83,2801554.72,2801554.72
6,2022-07,3395262.66,3395262.66,4238010.83,2801554.72,2801554.72
7,2022-08,3698942.66,3698942.66,4238010.83,2801554.72,2801554.72
8,2022-09,3854509.88,3854509.88,4238010.83,2801554.72,2801554.72
9,2022-10,3913434.52,3913434.52,4238010.83,2801554.72,2801554.72
10,2022-11,3520601.27,3520601.27,4238010.83,2801554.72,2801554.72
11,2022-12,4238010.83,4238010.83,4238010.83,2801554.72,2801554.72